### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by rosscarlson** [SayakMukhopadhyay/EDMC-Discord-Presence#2]
I've installed the plugin with EDMC but in Discord I only get something like CMDR Interface and it doesn't show my location.  I don't see anything to configure what am I missing?

**Comment by SayakMukhopadhyay** [comment]
Check if the presence disabled https://github.com/SayakMukhopadhyay/EDMC-Discord-Presence#options

**Comment by rosscarlson** [comment]
Nope, it sure isn't - is there any additional configuration, anything that needs to be done in Discord?

**Comment by SayakMukhopadhyay** [comment]
Nope. Since it's showing `Connecting to CMDR interface` it means the plugin was successfully able to communicate with Discord but since the data is not updating it means that either the plugin is not able read data from EDMC or EDMC is unable to read data. Please check if you are able to get status updates in the EDMC app itself.

**Comment by rosscarlson** [comment]
Yep, everything in EDMC is working perfectly, the main app and a few other plugings (like ExTool).  Many of my viewers are reporting the exact same thing so it seems something is up with the connection between the plugin and the data perhaps.  Are there any logs I can provide to help you track it down?  Is it working correctly for you?  Thanks for the help BTW.

**Comment by rosscarlson** [comment]
Any other ideas my friend?

**Comment by SayakMukhopadhyay** [comment]
Sorry for delayed reply. I am out on a work assignment with dodgy network. Unfortunately there is no logging. Maybe some API has changed in EDMC which is disrupting the data flow between EDMC and the plugin. I would need to play the game with EDMC and the plugin on to check this which I can't do before Saturday. Can you tell me the EDMC version so that I use the exact same version to test. Also the OS version. I only have Win10 with me so I hope you are on Win10 too 😝

**Comment by rosscarlson** [comment]
No problem my friend, not urgent, just didn't want it to get lost.  I'm using Windows 10 Pro and EDMC 3.12

**Comment by SayakMukhopadhyay** [comment]
Gotcha. I will ask around and see if other users have any issue until I get back.

**Comment by SayakMukhopadhyay** [comment]
I have found users not having problems on the same configuration. Can you post the logs under %TMP%\EDMarketConnector.log if any?

**Comment by VAKazakov** [comment]
i think all works to him now___

**Comment by SayakMukhopadhyay** [comment]
Ok, will close the issue for now. Feel free to reopen if needed.
