### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by alterNERDtive** [SayakMukhopadhyay/EDMC-Discord-Presence#7]
EDMC is going to switch to Python 3.7 with its 3.5.0 release. No idea if this plugin is still maintained, but I’d like to be able to keep using it. I also kind of don’t wanna fork it and fix it myself ;)

**Comment by Poneyy** [comment]
Hello,

I'm in the same situation as you...
I have some python notions, I did my best to make this plugin compatible for EDMC 3.5, but I'm far from being an expert.
It works fine, no errors reported by EDMC in the logs.

#8

**Comment by SayakMukhopadhyay** [comment]
Hi @Poneyy , I have merged your contribution in a separate branch since a bit of rework was required to make it English first. But thanks to your l10n contribution, I have decided to give some l10n in this plugin. As such, I will be reworking to include l10n before releasing the python3 compatibility.
